version: "3"

services:
  api:
    build:
      context: .
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8081:8080"
    volumes:
      # mount working directory
      # https://docs.docker.com/docker-for-mac/osxfs-caching/#delegated
      # the container’s view is authoritative (permit delays before updates on the container appear in the host)
      - .:/app:delegated

  nginx:
    build:
      context: ./nginx
    ports:
      - "8080:80"
    restart: unless-stopped
